[http]
proxy = "127.0.0.1:3080"

[actions.backend]
base = "backend"
watch = ["Cargo.toml", "Cargo.lock", "src/"]
run = ["cargo run"]
reload = "early"

[actions.frontend]
base = "frontend"
watch = [
    ".babelrc",
    ".eslintrc.js",
    "package-lock.json",
    "package.json",
    "tsconfig.json",
    "webpack.config.js",
    "src/",
]
run = [
    "npx tsc --skipLibCheck",
    "npx eslint src",
    "npx webpack --mode=development --display=errors-only",
]
reload = "late"
